name: Frontend Test
run-name: Frontend Test
on: [push]
jobs:
  Frontend-Test:
    runs-on: ubuntu-latest
    steps:              
    
      - uses: actions/checkout@v3
      
          
      - name: React Build Test
        run: |
          npm ci --production
          npm run build
        env:
           CI: false          
        working-directory: ./frontend


