name: Frontend Test
run-name: Frontend Test
on: [push]
jobs:
  Frontend-Test:
    runs-on: ubuntu-latest
    steps:              
    
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          check-latest: true 
      - run: rm -rf node_modules/
          
      - name: React Build Test
        run: |
          npm ci
          npm run build
        working-directory: ./frontend


